### ISSUE TITLE
Adding google-graphs compatibility

### ISSUE THREAD

**Issue by lethenju** [aduh95/schwifty-markdown#1]
I have to add bar charts on my document, and I **don't** want to waste any time on any other software to do so.
It would be really great if `schwifty-markdown` supported google-graphs or any other charts library.

Thank you

PS: Schwifty-Markdown is awesome!

**Comment by aduh95** [comment]
Hey @lethenju, thanks for your contribution!

Indeed adding some graph functionality into schwifty is very interesting.
That said, I am not sure [Google Charts](https://developers.google.com/chart/) *(I couldn't find any `google-graphs` you were referring to, please link to the library you are referring to next time)* is the best way to go since it requires network connection.

I have started to look around [Chartist](https://gionkunz.github.io/chartist-js) which seems to have the feature you need. Any thought on this?

It should land on v1.1, hopefully later this week!
